---
- name: Fetch package file
  unarchive:
    src: "{{ datagrid_package_url }}"
    dest: "{{ install_dir }}"
    owner: "{{ service.user }}"
    group: "{{ service.group }}"
    remote_src: true

- name: Fetch patch file
  get_url:
    url: "{{ patch.url }}"
    dest: "{{ install_dir }}/{{ patch.name }}"
    owner: "{{ service.user }}"
    group: "{{ service.group }}"
  loop: "{{ datagrid_patches | default([]) }}"
  loop_control:
    loop_var: patch